@url=http://localhost:3003/api
@json=Content-Type: application/json

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluNiIsImlhdCI6MTY4OTE1MTI0MX0.A9dfuiUj9u7yS3NFLcTvPE3Z9cK2oT6OLNgp0xxr16c

@auth=Authorization: {{token}}


### GET
get {{url}}/test


### 查询所有用户
get {{url}}/users?page=1&limit=10
{{auth}}


### 注册
post {{url}}/register
{{json}}

{
  "username": "admin6",
  "password": "admin"
}


### 登录
post {{url}}/login
{{json}}

{
  "username": "admin6",
  "password": "admin"
}



### 个人信息
get {{url}}/users/64adfcc25d662ba40034c385
{{auth}}


### 修改个人信息
post {{url}}/users/update
{{auth}}
{{json}}

{
  "id":"64adfcc25d662ba40034c385",
  "nickname": "aaaaa"
}


### 修改密码
post {{url}}/users/updatePassword
{{auth}}
{{json}}

{
  "id":"64adfcc25d662ba40034c385",
  "oldPassword": "qqqq",
  "newPassword": "admin"
}


### 删除用户
delete {{url}}/users/delete
{{auth}}
{{json}}

{
  "id":["64adfcc25d662ba40034c385"]
}



### 添加商品
post {{url}}/products
{{auth}}
{{json}}

{
  "name":"商品1",
  "price": 100,
  "desc": "商品1描述",
  "status": 1,
  "hot":false,
  "stock": 100
}



### 分页查询商品
get {{url}}/products
    ?page=1
    &limit=1
{{auth}}


### 查询商品 hot
get {{url}}/products/hot
    ?page=1
    &limit=10
{{auth}}



### 查询商品 new
get {{url}}/products/new
    ?page=1
    &limit=10
{{auth}}



### 查询商品详情
get {{url}}/products/64ae5d734c91a39a13221653
{{auth}}



### 修改商品
post {{url}}/products/64ae5d734c91a39a13221653
{{auth}}
{{json}}

{
  "name":"商品1",
  "price": 100,
  "desc": "商aaaa",
  "status": 1,
  "hot":false,
  "stock": 100
}



### 添加分类
post {{url}}/categories
{{auth}}
{{json}}

{
  "name":"分类22223",
  "desc": "分类3描述"
}



### 更新分类
post {{url}}/categories/64afadf798f595908710f64b
{{auth}}
{{json}}

{
  "name":"分类3",
  "desc": "分333述"
}


### 删除分类
delete {{url}}/categories/64afb8584411da1438cf973e
{{auth}}



### 获取所有分类
get {{url}}/categories/all
{{auth}}


### 查询分类 分页
get {{url}}/categories
    ?page=1
    &limit=10
{{auth}}



### 给商品添加类别
post {{url}}/products/addCats
{{auth}}
{{json}}

{
  "productId":"64ae676452fb05d51cfe7e5d",
  "categoryIds":["64afad51e64a2dbf7742dc26","64afad8e2cea8f4c69d13d6d"]
}


### 更新购物车
post {{url}}/cart/update
{{auth}}
{{json}}

{
  "userId":"64adfcc25d662ba40034c385",
  "products":[
    {
    "_id":"64ae676452fb05d51cfe7e5d",
    "quantity": 2
   },
   {
    "_id":"64ae5d734c91a39a13221653",
    "quantity": 1
   }
  ]
}

