@url=http://localhost:3003/api
@json=Content-Type: application/json

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluNiIsImlhdCI6MTY4OTE1MTI0MX0.A9dfuiUj9u7yS3NFLcTvPE3Z9cK2oT6OLNgp0xxr16c

@auth=Authorization: {{token}}


### GET
get {{url}}/test


### 查询所有用户
get {{url}}/users?page=1&limit=10
{{auth}}


### 注册
post {{url}}/register
{{json}}

{
  "username": "admin6",
  "password": "admin"
}


### 登录
post {{url}}/login
{{json}}

{
  "username": "admin6",
  "password": "admin"
}



### 个人信息
get {{url}}/users/64adfcc25d662ba40034c385
{{auth}}


### 修改个人信息
post {{url}}/users/update
{{auth}}
{{json}}

{
  "id":"64adfcc25d662ba40034c385",
  "nickname": "aaaaa"
}


### 修改密码
post {{url}}/users/updatePassword
{{auth}}
{{json}}

{
  "id":"64adfcc25d662ba40034c385",
  "oldPassword": "qqqq",
  "newPassword": "admin"
}


### 删除用户
delete {{url}}/users/delete
{{auth}}
{{json}}

{
  "id":["64adfcc25d662ba40034c385"]
}



### 添加商品
post {{url}}/products
{{auth}}
{{json}}

{
  "name":"商品1",
  "price": 100,
  "desc": "商品1描述",
  "status": 1,
  "hot":false,
  "stock": 100
}



### 分页查询商品
get {{url}}/products
    ?page=1
    &limit=1
{{auth}}


### 查询商品 hot
get {{url}}/products/hot
    ?page=1
    &limit=10
{{auth}}



### 查询商品 new
get {{url}}/products/new
    ?page=1
    &limit=10
{{auth}}



### 查询商品详情
get {{url}}/products/64ae5d734c91a39a13221653
{{auth}}


