openapi: 3.0.0
info:
  title: Mall API
  version: 1.0.0
paths:
  /api/test:
    get:
      summary: test
      responses:
        "200":
          description: OK
  /api/hello:
    get:
      summary: hello
      responses:
        "200":
          description: OK
