@url=http://localhost:3003/api
@json=Content-Type: application/json

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjg5NzY3MDQ5fQ.lDkA_Yx2oq7j9ATrxo7D2UBxJeEHNwTY2KB5xbNaQ5g

@auth=Authorization: {{token}}



### 获取购物车列表
get {{url}}/cart/64b2372bcdfa8c730d2566d2
{{auth}}


### 添加购物车
post {{url}}/cart/64b2372bcdfa8c730d2566d2
{{auth}}
{{json}}

{
"productId": "64b23bd6cdfa8c730d256724",
"quantity": "1"
}



### 从购物车移除
delete {{url}}/cart
{{auth}}
{{json}}

{
"productId": "64b23bd6cdfa8c730d256724",
"userId": "64b4f2c9acac9acd5b3654f4"
}



### 更新购物车商品数量
put {{url}}/cart
{{auth}}
{{json}}

{
	"userId":"64b2372bcdfa8c730d2566d2",
	"productId": "64b23bd6cdfa8c730d256724",
	"quantity": "222"
}
