@url=http://localhost:3003/api
@json=Content-Type: application/json

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluNiIsImlhdCI6MTY4OTI1MzI3OX0.OYzbYHKqGj0nmHjM2mLs8UsdqGx-FTe-qhQNvqTKIk4

@auth=Authorization: {{token}}


### GET
get {{url}}/test


### 查询所有用户
get {{url}}/users?page=1&limit=10
{{auth}}


### 注册
post {{url}}/register
{{json}}

{
  "username": "admin6",
  "password": "admin"
}


### 登录
post {{url}}/login
{{json}}

{
  "username": "admin6",
  "password": "admin"
}



### 个人信息
get {{url}}/users/64aff59b0861e50d839ba7f4
{{auth}}


### 修改个人信息
post {{url}}/users/update
{{auth}}
{{json}}

{
  "id":"64aff59b0861e50d839ba7f4",
  "nickname": "aaaaa"
}


### 修改密码
post {{url}}/users/updatePassword
{{auth}}
{{json}}

{
  "id":"64aff59b0861e50d839ba7f4",
  "oldPassword": "qqqq",
  "newPassword": "admin"
}


### 删除用户
delete {{url}}/users/delete
{{auth}}
{{json}}

{
  "id":["64aff59b0861e50d839ba7f4"]
}
